// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  require(['component'], function(Component) {
    var Collider;
    return Collider = (function(_super) {
      __extends(Collider, _super);

      function Collider(boundingShape) {
        this.boundingShape = boundingShape;
        this.name = 'collider';
      }

      return Collider;

    })(Component);
  });

}).call(this);
