// Generated by CoffeeScript 1.8.0
(function() {
  define([], function() {
    var Component;
    return Component = (function() {
      function Component() {
        this.name = "default";
      }

      Component.prototype.toString = function() {
        return this.name;
      };

      Component.prototype.addToEntity = function(e) {
        return e[this.name] = this;
      };

      return Component;

    })();
  });

}).call(this);
