// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  define([], function() {
    var Entity;
    return Entity = (function() {
      Entity.IDs = 0;

      function Entity() {
        var c, components, _i, _len;
        components = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        this.id = Entity.IDs++;
        for (_i = 0, _len = components.length; _i < _len; _i++) {
          c = components[_i];
          c.addToEntity(this);
        }
      }

      return Entity;

    })();
  });

}).call(this);
