// Generated by CoffeeScript 1.8.0
(function() {
  define(['entity'], function(Entity) {
    var EntityFactory;
    return EntityFactory = (function() {
      var factories;

      function EntityFactory() {}

      factories = [];

      EntityFactory.register = function(name, factory) {
        return factories[name] = factory;
      };

      EntityFactory["for"] = function(name) {
        return factories[name];
      };

      EntityFactory.prototype.build = function() {
        return new Entity();
      };

      return EntityFactory;

    })();
  });

}).call(this);
