// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['system'], function(System) {
    var EntityProcessingSystem;
    return EntityProcessingSystem = (function(_super) {
      __extends(EntityProcessingSystem, _super);

      function EntityProcessingSystem() {
        this.process = __bind(this.process, this);
        return EntityProcessingSystem.__super__.constructor.apply(this, arguments);
      }

      EntityProcessingSystem.prototype.processEntity = function(entity, dt) {};

      EntityProcessingSystem.prototype.process = function(dt) {
        var k, _i, _len, _ref, _results;
        _ref = Object.keys(this.entities);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          k = _ref[_i];
          _results.push(this.processEntity(this.entities[k], dt));
        }
        return _results;
      };

      return EntityProcessingSystem;

    })(System);
  });

}).call(this);
