// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["component", "vector"], function(Component, Vector) {
    var Flow;
    return Flow = (function(_super) {
      __extends(Flow, _super);

      function Flow(x, y) {
        if (x == null) {
          x = 0;
        }
        if (y == null) {
          y = 0;
        }
        this.name = "flow";
        this.vector = new Vector(x, y);
        this.range = 300;
        this.ang = 0.5;
      }

      return Flow;

    })(Component);
  });

}).call(this);
