// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["entityFactory", "entity", "position", "flow", "render"], function(EntityFactory, Entity, Position, Flow, Render) {
    var FlowFactory;
    return FlowFactory = (function(_super) {
      __extends(FlowFactory, _super);

      function FlowFactory() {
        return FlowFactory.__super__.constructor.apply(this, arguments);
      }

      EntityFactory.register("name", new FlowFactory());

      FlowFactory.build = function(x, y) {
        return new Entity(new Position(x, y), new Flow(0.5, 0), new Render(PIXI.Sprite.fromImage("../res/img/play.png")));
      };

      return FlowFactory;

    })(EntityFactory);
  });

}).call(this);
