// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['entityFactory', 'entity', 'fpsCounter', 'position'], function(EntityFactory, Entity, FpsCounter, Position) {
    var FpsCounterFactory;
    return FpsCounterFactory = (function(_super) {
      __extends(FpsCounterFactory, _super);

      function FpsCounterFactory() {
        return FpsCounterFactory.__super__.constructor.apply(this, arguments);
      }

      FpsCounterFactory.build = function(container) {
        var view;
        view = new PIXI.Text("-- FPS", {
          font: "20px Arial",
          fill: "red"
        });
        view.position.x = 10;
        view.position.y = 10;
        return new Entity(new FpsCounter(view));
      };

      return FpsCounterFactory;

    })(EntityFactory);
  });

}).call(this);
