// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["component"], function(Component) {
    var Gravition;
    return Gravition = (function(_super) {
      __extends(Gravition, _super);

      function Gravition(x, y) {
        if (x == null) {
          x = 0;
        }
        if (y == null) {
          y = 0;
        }
        this.name = "graviton";
        this.force = 1 / 8000;
        this.range = 500;
      }

      return Gravition;

    })(Component);
  });

}).call(this);
