// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["component", "vector"], function(Component, Vector) {
    var Lonely;
    return Lonely = (function(_super) {
      __extends(Lonely, _super);

      function Lonely() {
        this.name = "lonely";
        this.time = 0;
        this.vector = new Vector(0, 0);
      }

      return Lonely;

    })(Component);
  });

}).call(this);
