// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["entityProcessingSystem", "position", "velocity", "acceleration", "lonely", "vector"], function(EntityProcessingSystem, Position, Velocity, Acceleration, Lonely, Vector) {
    var LonelyMovement;
    return LonelyMovement = (function(_super) {
      __extends(LonelyMovement, _super);

      function LonelyMovement() {
        LonelyMovement.__super__.constructor.call(this, ["position", "acceleration", "lonely"]);
      }

      LonelyMovement.prototype.processEntity = function(e, dt) {
        if (e.lonely.time <= 0) {
          e.lonely.vector.x = -1 / 3000 + 2 * Math.random() / 3000;
          e.lonely.vector.y = -1 / 3000 + 2 * Math.random() / 3000;
          e.lonely.time = 300 + Math.random() * 500;
        }
        e.lonely.time -= dt;
        return e.acceleration.vector.add(e.lonely.vector);
      };

      return LonelyMovement;

    })(EntityProcessingSystem);
  });

}).call(this);
