// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["entityProcessingSystem", "position", "velocity", "acceleration", "vector"], function(EntityProcessingSystem, Position, Velocity, Acceleration, Vector) {
    var Movement;
    return Movement = (function(_super) {
      __extends(Movement, _super);

      function Movement() {
        this.processEntity = __bind(this.processEntity, this);
        Movement.__super__.constructor.call(this, ["position", "velocity"]);
      }

      Movement.prototype.processEntity = function(e, dt) {
        e.velocity.vector.add(Vector.mul(e.acceleration.vector, dt));
        return e.position.vector.add(Vector.mul(e.velocity.vector.mul(e.velocity.speed / e.velocity.vector.length()), dt));
      };

      return Movement;

    })(EntityProcessingSystem);
  });

}).call(this);
