// Generated by CoffeeScript 1.8.0
(function() {
  define(["vector"], function(Vector) {
    var PerlinNoise;
    return PerlinNoise = (function() {
      function PerlinNoise(seed) {
        this.seed = seed;
      }


      /*
       * this is not! perlin noise ... not enough time ...
       * values taken from delphigl.com
       * @return {integer} number between -1 and 1
       */

      PerlinNoise.prototype.perlin = function(x, y) {
        var n, rand;
        n = x + y * 57 + this.seed * 1000;
        n = (n << 13) ^ n;
        rand = 1 - ((n * (n * n * 15731 + 789221) + 1376312589) & 0x7fffffff) / 1073741824;
        return rand;
      };

      return PerlinNoise;

    })();
  });

}).call(this);
