// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['entityFactory', 'entity', 'pointCounter', 'position'], function(EntityFactory, Entity, PointCounter, Position) {
    var PointCounterFactory;
    return PointCounterFactory = (function(_super) {
      __extends(PointCounterFactory, _super);

      function PointCounterFactory() {
        return PointCounterFactory.__super__.constructor.apply(this, arguments);
      }

      PointCounterFactory.build = function(container) {
        var view;
        view = new PIXI.Text("Points: 00", {
          font: "20px Arial",
          fill: "red"
        });
        view.position.x = 600;
        view.position.y = 10;
        return new Entity(new PointCounter(view), new Position(1500, 1500));
      };

      return PointCounterFactory;

    })(EntityFactory);
  });

}).call(this);
