// Generated by CoffeeScript 1.8.0
(function() {
  define([], function() {
    var Queue;
    return Queue = (function() {
      function Queue() {
        this.data = [];
      }

      Queue.prototype.flip = function() {
        var tmp;
        tmp = [];
        while (this.data.length > 0) {
          tmp.push(this.data.pop);
        }
        return this.data = tmp;
      };

      Queue.prototype.push = function(v) {
        return this.data.push(v);
      };

      Queue.prototype.pop = function() {
        return this.data.pop;
      };

      Queue.prototype.isEmpty = function() {
        return this.data.length === 0;
      };

      return Queue;

    })();
  });

}).call(this);
