// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["component"], function(Component) {
    var Render;
    return Render = (function(_super) {
      __extends(Render, _super);

      function Render(sprite) {
        this.sprite = sprite;
        this.name = "render";
      }

      return Render;

    })(Component);
  });

}).call(this);
