// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["component"], function(Component) {
    var Swarm;
    return Swarm = (function(_super) {
      __extends(Swarm, _super);

      function Swarm() {
        this.name = "swarm";
        this.min = 30;
        this.max = 50;
        this.lose = 300;
        this.minForce = 1 / 1000;
        this.maxForce = 1 / 10000;
      }

      return Swarm;

    })(Component);
  });

}).call(this);
