// Generated by CoffeeScript 1.8.0
(function() {
  require(["swarm", "entity", "map", "vector"], function(Swarm, Entity, Map, Vector) {
    var dim, map, pos, tilesize, tres;
    console.log("SwarmMain");

    /*
    swarm = new Swarm
    entity = new Entity [60,80]
    swarm.entities.push(entity)
    swarm.run()
     */
    pos = new Vector(0, 0);
    tres = 1;
    dim = 4;
    tilesize = 100;
    map = new Map(pos, tres, dim, tilesize);
    return console.log(map.toString());
  });

}).call(this);
