// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var System;
    return System = (function() {
      function System(requiredComponents) {
        this.requiredComponents = requiredComponents;
        this.checkEntity = __bind(this.checkEntity, this);
        this.removeEntity = __bind(this.removeEntity, this);
        this.addEntity = __bind(this.addEntity, this);
        this.entities = [];
      }

      System.prototype.addEntity = function(entity) {
        this.entities[entity.id] = entity;
        return this.onEntityAdded(entity);
      };

      System.prototype.removeEntity = function(entity) {
        if (this.entities[entity.id] != null) {
          this.onEntityRemoved(entity);
          return delete this.entities[entity.id];
        }
      };

      System.prototype.onEntityAdded = function(entity) {};

      System.prototype.onEntityRemoved = function(entity) {};

      System.prototype.checkEntity = function(entity) {
        var c, _i, _len, _ref;
        _ref = this.requiredComponents;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          c = _ref[_i];
          if (entity[c] == null) {
            return;
          }
        }
        return this.addEntity(entity);
      };

      System.prototype.process = function(dt) {};

      return System;

    })();
  });

}).call(this);
