// Generated by CoffeeScript 1.8.0
(function() {
  define([], function() {
    var A;
    return A = (function() {
      function A() {}

      A.prototype.run = function() {
        return console.log("A");
      };

      return A;

    })();
  });

}).call(this);
