// Generated by CoffeeScript 1.8.0
(function() {
  define([], function() {
    var B;
    return B = (function() {
      function B() {}

      B.prototype.say = function(msg) {
        return console.log("B says: " + msg);
      };

      return B;

    })();
  });

}).call(this);
