// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["vector", "component"], function(Vector, Component) {
    var Velocity;
    return Velocity = (function(_super) {
      __extends(Velocity, _super);

      function Velocity(x, y) {
        if (x == null) {
          x = 0;
        }
        if (y == null) {
          y = 0;
        }
        this.name = "velocity";
        this.vector = new Vector(x, y);
        this.speed = 0.1;
      }

      return Velocity;

    })(Component);
  });

}).call(this);
